---

- name: Create configuration file for grafana-server
  template:
    src=grafana.ini.j2
    dest=/etc/grafana/grafana.ini
    owner=root
    group=grafana
    mode=0640
  become: yes
  become_user: grafana
  notify:
    - restart grafana-server