# Create grafana database and create grafana db user
---

- name: Install the python-psycopg2
  yum: name={{ python_psycopg2_yum_pkg }} state=present

- name: Create a dummy database for login_user
  become: yes
  become_user: postgres
  command: psql -c 'CREATE DATABASE {{ sky_db_admin_user }}'
  delegate_to: "{{ grafana_psql_host }}"
  authorized_key: user=vagrant key="{{ lookup('file', '/vagrant/.ssh/id_rsa.pub') }}" 

- name: Create postgres grafana user
  postgresql_user: login_host={{ grafana_psql_host }} 
                   login_user={{ sky_db_admin_user }} 
                   login_password={{ sky_db_admin_password }}
                   name={{ grafana_db_user }} 
                   password={{ grafana_db_pass }}  
                   port={{ grafana_psql_port }}
                   role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER

- name: Create postgres grafana db
  postgresql_db: login_host={{ grafana_psql_host }}
                 login_user={{ sky_db_admin_user }}
                 login_password={{ sky_db_admin_password }}
                 name={{ grafana_db_name }}
                 encoding='UTF-8'
                 lc_collate='tr_TR.UTF-8'
                 lc_ctype='tr_TR.UTF-8'
                 template='template0'
                 owner={{ grafana_db_user }}
                 port={{ grafana_psql_port }}