# Create grafana database and create grafana db user
---

- name: Install the python-psycopg2
  yum: name={{ python_psycopg2_yum_pkg }} state=present

# First log in to the remote postgresql server, create a db and a role with the name of sky_db_admin_user. 
# And than alter the same role with SUPERUSER, LOGIN, CREATEDB and CREATEROLE 
- name: Create postgres grafana user
  postgresql_user: login_host={{ grafana_psql_host }} 
                   login_user={{ sky_db_admin_user }} 
                   login_password={{ sky_db_admin_password }}
                   name={{ grafana_db_user }} 
                   password={{ grafana_db_pass }}  
                   port={{ grafana_psql_port }}
                   role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER

- name: Create postgres grafana db
  postgresql_db: login_host={{ grafana_psql_host }}
                 login_user={{ sky_db_admin_user }}
                 login_password={{ sky_db_admin_password }}
                 name={{ grafana_db_name }}
                 encoding='UTF-8'
                 lc_collate='tr_TR.UTF-8'
                 lc_ctype='tr_TR.UTF-8'
                 template='template0'
                 owner={{ grafana_db_user }}
                 port={{ grafana_psql_port }}