# Main tasks file for grafana-server
---

# OS check
- name: Checking OS family is supported
  fail: msg='Unfortunately {{ ansible_os }}-like operating systems are not supported by this role.'
  when: ansible_os not in supported_os

# Install grafana-server
- include: install.yml

# Grafana db installation & user creation
- include: create_db.yml

# Configure grafana-server
- include: config.yml


