---

- name: Create configuration file for grafana-server
  template:
    src=grafana.ini.j2
    dest=/etc/grafana/grafana.ini
    owner=root
    group=grafana
    mode=0640
  notify:
    - restart grafana-server

- name: Restart grafana-server
  service: name=grafana-server state=restarted